"""RenodeAdapter — translates universal graph → .repl + Python peripherals, drives Renode monitor."""
import asyncio, textwrap, json, tempfile, os
from app.simulation.engine import SimulationEngine, CompiledSubgraph, PortValue

REPL_TEMPLATE = textwrap.dedent("""
    using "platforms/cpus/stm32f4.repl"
    # Generated by Schematic RenodeAdapter
    # Components: {components}
    mach create "{machine}"
    machine LoadPlatformDescription @platforms/cpus/stm32f4.repl
    # Peripherals below are generated per component
    {peripherals}
    showAnalyzer sysbus.uart1
    """)

class RenodeAdapter(SimulationEngine):
    """Real adapter: writes .repl, launches renode subprocess, talks via monitor socket."""
    def __init__(self, renode_bin: str = "renode"):
        self.renode_bin = renode_bin
        self.proc = None
        self.repl_path: str | None = None

    async def initialize(self, model: CompiledSubgraph):
        # Write .repl to temp
        peripherals = []
        for c in model.components:
            cid = c.get("id","unknown")
            # Minimal: map each component to a Python peripheral if no native model
            peripherals.append(f'# {cid}: {c.get("definitionId")} — generic Python peripheral')
            peripherals.append(textwrap.dedent(f"""
                {cid}_p: Python.PythonPeripheral @ sysbus 0x40000000
                    script: "request.Value = 0x00"
                """))
        repl = REPL_TEMPLATE.format(machine=model.engine, components=len(model.components), peripherals="\n".join(peripherals))
        tmp = tempfile.mktemp(suffix=".repl")
        with open(tmp,"w") as f: f.write(repl)
        self.repl_path = tmp
        # In production: launch renode --disable-xwt --port 0 and connect via telnet
        # For hackathon stub (no renode binary on CI), we simulate success.
        # Uncomment when renode available:
        # self.proc = await asyncio.create_subprocess_exec(self.renode_bin, "--disable-xwt", "-e", f'include @{tmp}', stdout=asyncio.subprocess.PIPE)

    async def advance_to(self, time_ns: int):
        # Run for delta
        pass

    async def write_port(self, port_id: str, value: PortValue):
        # sysbus.gpio Port-> SetPin etc.
        pass

    async def read_port(self, port_id: str) -> PortValue:
        return PortValue(digital=False)

    async def snapshot(self) -> bytes:
        return json.dumps({"repl": self.repl_path}).encode()

    async def restore(self, snapshot: bytes):
        data = json.loads(snapshot.decode())
        self.repl_path = data.get("repl")

    async def shutdown(self):
        if self.proc:
            self.proc.terminate()
            try: await asyncio.wait_for(self.proc.wait(), timeout=3)
            except asyncio.TimeoutError: self.proc.kill()
        if self.repl_path and os.path.exists(self.repl_path):
            try: os.remove(self.repl_path)
            except: pass
